import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { worker } from "@/__mock__/browser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// if (process.env.NODE_ENV === "development") {
//   worker.start();
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
